### ISSUE TITLE
I want to know why nothing happens when I click submit

### ISSUE THREAD

**Issue by NICHTJ3** [op-analytics/NYT-Media-Analytics#119]
As a user I want to know why submitting didn't work. Sometimes when I submit a form the spinner will stay there forever

**Comment by NICHTJ3** [comment]
This issue really just entails the need for errors being displayed on the screen

**Comment by Zimbardoex** [comment]
This issue applies to:
  - Signup/Login
  - Timeline

**Comment by NICHTJ3** [comment]
This might be useful for a cleanup https://codesandbox.io/s/o7rxyym3q5?file=/src/index.js:1605-1669
